### ISSUE TITLE
Option for xwidget browser

### ISSUE THREAD

**Issue by xsrvmy** [jakebox/org-preview-html#11]
Will you add support for xwidget browser? So math can be previewed.

**Comment by lujun9972** [comment]
xwidget browser seems not usable enough.
and also, I am not familiar with the xwidget browser, so I am afraid I can't add the support.
But if you could pull the request, I will merge it.

**Comment by lujun9972** [comment]
@tumashu will you help?

**Comment by jakebox** [comment]
Hello to this old thread. I wrote a similar package called `preview-org-html-mode` without having seen `org-preview-html` which does essentially what `org-preview-html` does but with the xwidget browser. What do you think? Maybe we can compare/maybe look to combine some functionality?

https://github.com/jakebox/preview-org-html-mode

**Comment by lujun9972** [comment]
@jakebox Sorry for the late response. 

It would be great if you could help, Would you like to be a collaborator?

**Comment by yugaego** [comment]
The demo with the xwidget looks exactly what I was looking for a year ago.
In my opinion it'd be great to have both eww/xwidget preview in out-of-the-box org.
@lujun9972, @jakebox Have you considered/tried suggesting preview functionality to be added to the org code?

**Comment by lujun9972** [comment]
I haven't suggested it before, and I think it is not an indispensable part of org because it is already pretty straightforward.

**Comment by yugaego** [comment]
>  it is not an indispensable part of org because it is already pretty straightforward.

No pressure ;-) just my experience: when I was making my first steps with `Emacs` and `org-mode` it was very **not** trivial for me to find and install this package. And figure out in the first place the feature was not provided natively by org-mode. I suppose there's a high chance it'd be added sooner or (rather :sigh:) later.
[It seemed to me the `org-mode` community was quite responsive to the patches
(though I've only lurked on their mailing list).]

And BTW, thank you for the package, it helped a lot along the way!

**Comment by yugaego** [comment]
My previous comment made me thinking that potentially adding `org-preview` package(s) to [GNU ELPA](http://elpa.gnu.org) or at least [NonGNU  ELPA](https://emacsredux.com/blog/2021/08/11/submitting-a-package-to-nongnu-elpa/) could increase the visibility of the package(s).
Anyway, I would be thrilled to see you cooperating guys and combining eww/xwidget preview into one project (or at least under one namespace to avoid names confusion on usage). Thanks!

**Comment by jakebox** [comment]
@yugaego @lujun9972 Hi! Thanks for the reply. In fact, I added `eww` functionality to my package.

https://github.com/jakebox/preview-org-html-mode/commit/56a90e4781e64812471f726f66221d20fb96e46c

I am trying to get my package into MELPA but the issue is the naming conflict with this package, `org-preview-html`. You can see that thread here:

https://github.com/melpa/melpa/pull/7669

My worry about being a contributor on this package is that my package's code is quite different as it has support for xwidgets and eww, better buffer/window cleanup, and multiple save modes. I feel like if I were to add my functionality I would be simply replacing all of your code, which doesn't feel right. I also have plans to continue adding functionality for external browsers like Firefox, Chrome, etc.

Frankly I'm not sure what the next steps are. I agree that the namespaces are confusing, and my package is poorly named. However, I don't want to just merge my code into `org-preview-html` as the way our code is laid out is a bit different.

What do you think? We can move this discussion over to the MELPA thread, or @alphapapa can chime in over here with his thoughts, he is the one who brought this situation to my attention.

**Comment by lujun9972** [comment]
@jakebox
I am OK about replacing all the code, please just keep the default behavior.
Also, considering my lack of time to maintaining this repo, I can transfer this repo to you if you wish.

**Comment by alphapapa** [comment]
@lujun9972 Thanks for your flexibility and humility.  You put the users first, which is what all maintainers should do.

**Comment by jakebox** [comment]
^ Seconded.

**Comment by lujun9972** [comment]
![图片](https://user-images.githubusercontent.com/6605174/130558698-3c620fb5-215a-4cd0-8930-b2f38660d4b5.png)

**Comment by jakebox** [comment]
Xwidget support added – closed!

**Comment by yugaego** [comment]
Feedback: the package upgrade went smoothly and the live preview looks real great! Thank you for your work, @jakebox !

**Comment by jakebox** [comment]
@yugaego Thanks so much, I really appreciate the feedback (good to know!) and thanks for your nice words.
